settings:
  debug: false
  storage:
      type: SQLITE
      host: "localhost"
      port: 3306
      username: "root"
      password: "password"
      database: "playertags_data"
  gui:
    size: 45
    show-no-perm: true
    item:
      has-perm: NAME_TAG
      no-perm: BARRIER
tags:
  meme:
    type: 'PREFIX'
    prefix: '&d[&lMeme&d]'
    description: "A true meme"
    permission: false
  og:
    type: 'SUFFIX'
    prefix: '&b[&lOG&b]'
    description: "Much OG, Much Wow"
    permission: true
    item:
      has-perm:
        item: DIAMOND
        name: "&aOG Tag"
        lore:
          - '&7Customise in the config!'
      no-perm:
        item: REDSTONE
        name: "&cOG Tag"
        lore:
          - '&7Customise in the config!'
          - '&7&oNo perms :/'