settings:
  debug: false
  autosave: true
  chat-format:
    enabled: true
    format: "&7[%vault_prefix%] &f%player_name%&a%playertags_prefix%&7: %message%"
  storage:
      type: SQLITE
      host: "localhost"
      port: 3306
      username: "root"
      password: "password"
      database: "playertags_data"
  gui:
    size: 45
    show-no-perm: true
    item:
      has-perm: NAME_TAG
      no-perm: BARRIER
tags: {}