settings:
  debug: true
  gui:
    size: 45
    show-no-perm: true
tags:
  meme:
    prefix: '&d[&lMeme&d]'
    description: "A true meme"
    permission: false
  og:
    prefix: '&b[&lOG&b]'
    description: "Much OG, Much Wow"
    permission: true
