## PlayerTags - v1.0 ##

settings:
    gui:
      title: "[{0}/{1}] Player Tags ({2}/{3} Unlocked)"

tags:
  example:
      prefix: "&7[Example]"
      description: "This is an example tag, r/woosh"
      permission: false