name: ${plugin}
version: ${project.version}
main: ${package}
author: "CodeItForYou"
website: https://codeitforyou.com/
description: "Let players use custom tag prefixes beside their name."
softdepend: ["PlaceholderAPI"]

permissions:
  cifytags.*:
    description: Gives access to all PlayerTags commands
    children:
      cifytags.create: true
      cifytags.remove: true
      cifytags.help: true
      cifytags.list: true
      cifytags.reload: true
      cifytags.setdesc: true
      cifytags.setprefix: true
      cifytags.version: true
  cifytags.create:
    default: op
  cifytags.remove:
    default: op
  cifytags.help:
    default: op
  cifytags.list:
    default: op
  cifytags.reload:
    default: op
  cifytags.setdesc:
    default: op
  cifytags.setprefix:
    default: op
  cifytags.version:
    default: op